import React, { useState } from 'react';

const FAQs = () => {

    const [openIndex, setOpenIndex] = useState(null);

    const styles = `
        @import url('https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css');

        .faq-page-container {
            background-color: #f8f9fa;
            color: #212529;
            padding-bottom: 4rem;
        }

        .faq-hero {
            background: linear-gradient(45deg, #007bff, #0056b3);
            padding: 4rem 0;
            margin-bottom: 3rem;
        }

        .faq-hero h1 {
            font-weight: 700;
        }

        .faq-accordion {
            max-width: 800px;
            margin: 0 auto;
        }

        .faq-item {
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            margin-bottom: 1rem;
            overflow: hidden; /* Important for the answer transition */
        }

        .faq-question {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1.25rem 1.5rem;
            cursor: pointer;
            font-size: 1.1rem;
            font-weight: 600;
        }

        .faq-answer {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out, padding 0.3s ease-out;
            padding: 0 1.5rem;
        }

        .faq-answer p {
            margin-bottom: 1.25rem;
            line-height: 1.6;
        }

        .faq-item.open .faq-answer {
            max-height: 300px; /* Adjust if answers are longer */
            padding: 0 1.5rem 1.25rem 1.5rem;
            transition: max-height 0.4s ease-in, padding 0.4s ease-in;
        }
        
        .faq-toggle-icon {
            font-size: 1.5rem;
            font-weight: 300;
            transition: transform 0.3s ease;
        }

        .faq-item.open .faq-toggle-icon {
            transform: rotate(45deg);
        }

        .dark-theme .faq-page-container {
            background-color: #121212;
            color: #f1f1f1;
        }

        .dark-theme .faq-item {
            background-color: #1e1e1e;
            border-color: #333;
        }
    `;

    const faqData = [
        {
            question: "What is DocSwitch?",
            answer: "DocSwitch is a free online platform that provides a comprehensive suite of tools for converting, editing, and managing a wide variety of document and media files. Our goal is to make file management simple, fast, and accessible to everyone."
        },
        {
            question: "Is DocSwitch completely free to use?",
            answer: "Yes! All tools available on DocSwitch are 100% free. There are no hidden costs, subscription fees, or limits on the number of conversions you can perform."
        },
        {
            question: "How does the AI Question Generator work?",
            answer: "Our AI Question Generator utilizes the powerful Google Gemini API. You upload a document (like a PDF), and the AI analyzes the content to generate relevant questions and answers, creating instant study guides or quizzes."
        },
        {
            question: "Can I customize the questions generated by the AI?",
            answer: "Absolutely. You have full control over the output. You can specify the number of questions you need and set a custom difficulty level (e.g., easy, medium, hard) to tailor the questions to your exact requirements. Once generated, you can view the answers directly on the page or download a file with a complete answer sheet."
        },
        {
            question: "Are the files I upload to DocSwitch secure?",
            answer: "Yes, security is our top priority. We use secure connections for all file transfers. Your uploaded files are only used for the conversion process and are automatically deleted from our servers after a short period to ensure your privacy."
        },
        {
            question: "Why is my file conversion sometimes slow?",
            answer: "DocSwitch functions by integrating with reliable third-party APIs for file processing. While this allows us to offer a wide range of high-quality tools, the conversion speed can occasionally depend on the current server load of these external services. We appreciate your patience and are always working to optimize performance."
        },
        {
            question: "Do I need to create an account to use the tools?",
            answer: "No account is required. You can start using all our tools immediately without any registration, making the process quick and hassle-free."
        },
        {
            question: "What kind of tools do you offer besides file conversion?",
            answer: "Beyond simple format conversions, we offer a variety of document management tools, including PDF merging, splitting, compression, signing, and watermarking to cover all your needs."
        },
        {
            question: "Can I use DocSwitch on my mobile phone or tablet?",
            answer: "Yes! Our website is fully responsive, which means you can access and use all our tools on any device, including desktops, tablets, and smartphones, without any loss of functionality."
        }
    ];

    const handleToggle = (index) => {
        if (openIndex === index) {
            setOpenIndex(null); 
        } else {
            setOpenIndex(index); 
        }
    };

    return (
        <>
            <style>{styles}</style>
            <div className="faq-page-container">

                <header className="faq-hero text-white text-center">
                    <div className="container">
                        <h1 className="display-4">Frequently Asked Questions</h1>
                        <p className="lead">
                            Have a question? We're here to help.
                        </p>
                    </div>
                </header>

                <div className="container">
                    <div className="faq-accordion">
                        {faqData.map((item, index) => (
                            <div key={index} className={`faq-item ${openIndex === index ? 'open' : ''}`}>
                                <div className="faq-question" onClick={() => handleToggle(index)}>
                                    <span>{item.question}</span>
                                    <span className="faq-toggle-icon">+</span>
                                </div>
                                <div className="faq-answer">
                                    <p>{item.answer}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </>
    );
};

export default FAQs;
